import ProductCard from "./ProductCard";
import { Link } from "react-router-dom";
import "../css/ProductListing.css";
import { FaArrowRightLong } from "react-icons/fa6";


export const lista = [
  // Pants
  { id: 1, image:"/src/public/product-images/calca1.jpg", name: "Calça 1", price: 381.77, color: ["Gray", "Black", "Blue"], size: ["36", "38", "40", "42", "44"], discount: 15, category: "pants", gender: "female", brand: "Sony", rating: 3.6, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores"}, 
  { id: 2, image:"/src/public/product-images/calca2.jpg", name: "Calça 2", price: 478.10, color: ["Gray", "Blue", "Beige"], size: ["36", "38", "40", "42", "44"], discount: 15, category: "pants", gender: "unisex", brand: "Levis", rating: 4.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 3, image:"/src/public/product-images/calca3.jpg", name: "Calça 3", price: 446.25, color: ["Gray", "Green", "Beige"], size: ["36", "38", "40", "42", "44"], discount: 5, category: "pants", gender: "male", brand: "Sony", rating: 3.4, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 4, image:"/src/public/product-images/calca4.jpg", name: "Calça 4", price: 288.33, color: ["Blue", "Black", "Beige"], size: ["36", "38", "40", "42", "44"], discount: 10, category: "pants", gender: "male", brand: "Nike", rating: 4.2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 5, image:"/src/public/product-images/calca5.jpg", name: "Calça 5", price: 198.90, color: ["Black", "Green"], size: ["36", "38", "40", "42", "44"], discount: 0, category: "pants", gender: "female", brand: "Adidas", rating: 4.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },

  // Sneakers
  { id: 6, image:"/src/public/product-images/tenis6.jpg", name: "Sneaker Model 6", price: 69.15, color: ["White", "Gray", "Red"], size: ["38", "39", "40", "41", "42"], discount: 15, category: "sneaker", gender: "male", brand: "Levis", rating: 3.7, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 7, image:"/src/public/product-images/tenis7.jpg", name: "Sneaker Model 7", price: 475.67, color: ["Red", "White", "Gray"], size: ["38", "39", "40", "41", "42"], discount: 15, category: "sneaker", gender: "male", brand: "Hering", rating: 4.8, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 8, image:"/src/public/product-images/tenis8.jpg", name: "Sneaker Model 8", price: 322.99, color: ["Black", "White"], size: ["38", "39", "40", "41", "42"], discount: 20, category: "sneaker", gender: "unisex", brand: "Nike", rating: 4.5, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 9, image:"/src/public/product-images/tenis9.jpg", name: "Sneaker Model 9", price: 289.90, color: ["Blue", "Gray"], size: ["38", "39", "40", "41", "42"], discount: 10, category: "sneaker", gender: "female", brand: "Adidas", rating: 4.3, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 10, image:"/src/public/product-images/tenis10.jpg", name: "Sneaker Model 10", price: 399.00, color: ["Black", "Red"], size: ["38", "39", "40", "41", "42"], discount: 5, category: "sneaker", gender: "female", brand: "Nike", rating: 4.1, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },

  // T-Shirts
  { id: 11, image:"/src/public/product-images/camiseta11.jpg", name: "T-Shirt Model 11", price: 89.90, color: ["White", "Black"], size: ["S", "M", "L", "XL", "XXL"], discount: 10, category: "tshirt", gender: "male", brand: "Hering", rating: 4.2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 12, image:"/src/public/product-images/camiseta12.jpg", name: "T-Shirt Model 12", price: 79.90, color: ["Gray", "Green"], size: ["S", "M", "L", "XL", "XXL"], discount: 0, category: "tshirt", gender: "unisex", brand: "Nike", rating: 3.9, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 13, image:"/src/public/product-images/camiseta13.jpg", name: "T-Shirt Model 13", price: 99.90, color: ["White", "Yellow"], size: ["S", "M", "L", "XL", "XXL"], discount: 5, category: "tshirt", gender: "female", brand: "Adidas", rating: 4.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 14, image:"/src/public/product-images/camiseta14.jpg", name: "T-Shirt Model 14", price: 69.90, color: ["Green", "Black"], size: ["S", "M", "L", "XL", "XXL"], discount: 20, category: "tshirt", gender: "unisex", brand: "Levis", rating: 4.4, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 15, image:"/src/public/product-images/camiseta15.jpg", name: "T-Shirt Model 15", price: 89.90, color: ["Black", "Gray"], size: ["S", "M", "L", "XL", "XXL"], discount: 0, category: "tshirt", gender: "male", brand: "New Era", rating: 4.1, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },

  // Caps
  { id: 16, image:"/src/public/product-images/bone16.jpg", name: "Cap Model 16", price: 110.11, color: ["Red", "Blue", "Black"], size: ["One Size"], discount: 10, category: "cap", gender: "unisex", brand: "Nike", rating: 4.7, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 17, image:"/src/public/product-images/bone17.jpg", name: "Cap Model 17", price: 122.77, color: ["White", "Red", "Green"], size: ["One Size"], discount: 20, category: "cap", gender: "male", brand: "Adidas", rating: 3.2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 18, image:"/src/public/product-images/bone18.jpg", name: "Cap Model 18", price: 139.90, color: ["Black", "Blue"], size: ["One Size"], discount: 5, category: "cap", gender: "female", brand: "New Era", rating: 4.3, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 19, image:"/src/public/product-images/bone19.jpg", name: "Cap Model 19", price: 99.90, color: ["Black"], size: ["One Size"], discount: 0, category: "cap", gender: "unisex", brand: "Levis", rating: 4.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 20, image:"/src/public/product-images/bone20.jpg", name: "Cap Model 20", price: 109.00, color: ["Blue", "White"], size: ["One Size"], discount: 15, category: "cap", gender: "male", brand: "Nike", rating: 4.1, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },

  // Headphones
  { id: 21, image:"/src/public/product-images/headphone21.jpg", name: "Headphone Model 21", price: 337.58, color: ["Red", "Blue", "Black"], size: ["One Size"], discount: 15, category: "headphone", gender: "unisex", brand: "Sony", rating: 5.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 22, image:"/src/public/product-images/headphone22.jpg", name: "Headphone Model 22", price: 289.90, color: ["Black", "White"], size: ["One Size"], discount: 10, category: "headphone", gender: "female", brand: "JBL", rating: 4.6, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 23, image:"/src/public/product-images/headphone23.jpg", name: "Headphone Model 23", price: 349.00, color: ["Pink", "White"], size: ["One Size"], discount: 20, category: "headphone", gender: "female", brand: "Sony", rating: 4.8, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 24, image:"/src/public/product-images/headphone24.jpg", name: "Headphone Model 24", price: 319.90, color: ["Black", "Red"], size: ["One Size"], discount: 5, category: "headphone", gender: "unisex", brand: "JBL", rating: 4.2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 25, image:"/src/public/product-images/headphone25.jpg", name: "Headphone Model 25", price: 429.90, color: ["White"], size: ["One Size"], discount: 0, category: "headphone", gender: "male", brand: "Sony", rating: 4.9, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" }
];



export function ProductListing ({title, link, limit, onAddToCart}){
    const produtosexibidos = limit ? lista.slice(0, limit) : lista;

    return(
        <div className="product-listing">
            <div className="header flex items-center justify-between info ">
                {title && <h2 className="text-[var(--darkgray2)] text-[24px] font-bold">{title}</h2>}
                {link && 
                    <Link to={link.src}>
                        <h2 className="text-[var(--principal)] flex gap-3 items-center">
                            {link.text} <FaArrowRightLong /> 
                        </h2>
                    </Link>
                }
            </div>
            <ProductCard lista = {produtosexibidos} onAddToCart={onAddToCart}/>
        </div>
    )
}