import ProductCard from "./ProductCard";
import { Link } from "react-router-dom";
import "../css/ProductListing.css";
import { FaArrowRightLong } from "react-icons/fa6";


export const lista = [
  // Pants
  { id: 1, image:"/src/public/product-images/calca.jpg", name: "Calça Hering", price: 381.77, color: ["Gray", "Black", "Blue"], size: ["36", "38", "40", "42", "44"], discount: 15, category: "pants", gender: "female", brand: "Hering", rating: 3.6, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores"}, 
  { id: 2, image:"/src/public/product-images/calca1.jpg", name: "Calça Hering", price: 478.10, color: ["Gray", "Blue", "Beige"], size: ["36", "38", "40", "42", "44"], discount: 15, category: "pants", gender: "male", brand: "Hering", rating: 4.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 3, image:"/src/public/product-images/calca2.jpg", name: "Calça Hering", price: 446.25, color: ["Gray", "Green", "Beige"], size: ["36", "38", "40", "42", "44"], discount: 5, category: "pants", gender: "unisex", brand: "Hering", rating: 3.4, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 4, image:"/src/public/product-images/pants4.jpg", name: "Calça Hering", price: 288.33, color: ["Blue", "Black", "Beige"], size: ["36", "38", "40", "42", "44"], discount: 10, category: "pants", gender: "unisex", brand: "Hering", rating: 4.2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 5, image:"/src/public/product-images/pants5.jpg", name: "Calça Hering", price: 198.90, color: ["Black", "Green"], size: ["36", "38", "40", "42", "44"], category: "pants", gender: "female", brand: "Hering", rating: 4.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },

  // Sneakers
  { id: 6, image:"/src/public/product-images/tenis6.jpg", name: "Sneaker Air jordan", price: 69.15, color: ["White", "Gray", "Red"], size: ["38", "39", "40", "41", "42"], discount: 15, category: "sneaker", gender: "male", brand: "NIKE", rating: 3.7, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 7, image:"/src/public/product-images/tenis7.jpg", name: "Sneaker PUMA", price: 475.67, color: ["Red", "White", "Gray"], size: ["38", "39", "40", "41", "42"], discount: 15, category: "sneaker", gender: "male", brand: "Hering", rating: 4.8, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 8, image:"/src/public/product-images/tenis8.jpg", name: "Sneaker ADIDAS", price: 322.99, color: ["Black", "White"], size: ["38", "39", "40", "41", "42"], discount: 20, category: "sneaker", gender: "unisex", brand: "Nike", rating: 4.5, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 9, image:"/src/public/product-images/adidas1.jpg", name: "Sneaker ADIDAS", price: 289.90, color: ["Blue", "Gray"], size: ["38", "39", "40", "41", "42"], discount: 10, category: "sneaker", gender: "female", brand: "Adidas", rating: 4.3, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 10, image:"/src/public/product-images/tenis5.jpg", name: "Sneaker NIKE", price: 399.00, color: ["Black", "Red"], size: ["38", "39", "40", "41", "42"], discount: 5, category: "sneaker", gender: "female", brand: "Nike", rating: 4.1, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },

  // T-Shirts
  { id: 11, image:"/src/public/product-images/t-shirt7.jpg", name: "T-Shirt Hosek", price: 89.90, color: ["White", "Black"], size: ["S", "M", "L", "XL", "XXL"], discount: 10, category: "tshirt", gender: "male", brand: "Hosek", rating: 4.2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 12, image:"/src/public/product-images/t-shirt5.jpg", name: "T-Shirt Hering", price: 79.90, color: ["Gray", "Green"], size: ["S", "M", "L", "XL", "XXL"], category: "tshirt", gender: "male", brand: "Hering", rating: 3.9, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 13, image:"/src/public/product-images/camiseta13.jpg", name: "T-Shirt New era", price: 99.90, color: ["White", "Yellow"], size: ["S", "M", "L", "XL", "XXL"], discount: 5, category: "tshirt", gender: "female", brand: "New era", rating: 4.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 14, image:"/src/public/product-images/t-shirt6.jpg", name: "T-Shirt Cloth", price: 69.90, color: ["Green", "Black"], size: ["S", "M", "L", "XL", "XXL"], discount: 20, category: "tshirt", gender: "unisex", brand: "Cloth", rating: 4.4, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 15, image:"/src/public/product-images/t-shirt4.jpg", name: "T-Shirt New era", price: 89.90, color: ["Black", "Gray"], size: ["S", "M", "L", "XL", "XXL"], category: "tshirt", gender: "male", brand: "New Era", rating: 4.1, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },

  // Caps
  { id: 16, image:"/src/public/product-images/bone16.jpg", name: "Cap HERING", price: 110.11, color: ["Red", "Blue", "Black"], size: ["One Size"], discount: 10, category: "cap", gender: "unisex", brand: "Hering", rating: 4.7, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 17, image:"/src/public/product-images/bone17.jpg", name: "Cap DOPE", price: 122.77, color: ["White", "Red", "Green"], size: ["One Size"], discount: 20, category: "cap", gender: "unisex", brand: "DOPE", rating: 3.2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 18, image:"/src/public/product-images/cap1.jpg", name: "Cap NIKE", price: 139.90, color: ["Black", "Blue"], size: ["One Size"], discount: 5, category: "cap", gender: "unisex", brand: "NIKE", rating: 4.3, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 19, image:"/src/public/product-images/cap2.jpg", name: "Cap Ovrnight", price: 99.90, color: ["Black"], size: ["One Size"], category: "cap", gender: "male", brand: "OVRNIGHT", rating: 4.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 20, image:"/src/public/product-images/bone20.jpg", name: "Cap Disorder", price: 109.00, color: ["Blue", "White"], size: ["One Size"], discount: 15, category: "cap", gender: "male", brand: "Disorder", rating: 4.1, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },

  // Headphones
  { id: 21, image:"/src/public/product-images/headphoneapple.jpg", name: "Headphone APPLE", price: 337.58, color: ["Red", "Blue", "Black"], size: ["One Size"], discount: 15, category: "headphone", gender: "female", brand: "APPLE", rating: 5.0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 22, image:"/src/public/product-images/headphonejbl.jpg", name: "Headphone JBL", price: 289.90, color: ["Black", "White"], size: ["One Size"], discount: 10, category: "headphone", gender: "male", brand: "JBL", rating: 4.6, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 23, image:"/src/public/product-images/headphoneaudio-technica.jpg", name: "Headphone Audio-Technica", price: 349.00, color: ["Pink", "White"], size: ["One Size"], discount: 20, category: "headphone", gender: "male", brand: "Audio-Technica", rating: 4.8, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 24, image:"/src/public/product-images/headphonesony.jpg", name: "Headphone SONY", price: 319.90, color: ["Black", "Red"], size: ["One Size"], discount: 5, category: "headphone", gender: "unisex", brand: "SONY", rating: 4.2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" },
  { id: 25, image:"/src/public/product-images/headphone25.jpg", name: "Headphone SONY", price: 429.90, color: ["White"], size: ["One Size"], category: "headphone", gender: "male", brand: "SONY", rating: 4.9, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis dicta fugit harum aspernatur saepe corrupti quo assumenda labore deserunt at. Assumenda atque illum magnam incidunt molestias officiis cupiditate alias! Asperiores" }
];



export function ProductListing ({title, link, limit, onAddToCart}){
    const produtosexibidos = limit ? lista.slice(0, limit) : lista;

    return(
        <div className="product-listing">
            <div className="header flex items-center justify-between info ">
                {title && <h2 className="text-[var(--darkgray2)] text-[24px] font-bold">{title}</h2>}
                {link && 
                    <Link to={link.src}>
                        <h2 className="text-[var(--principal)] flex gap-3 items-center">
                            {link.text} <FaArrowRightLong /> 
                        </h2>
                    </Link>
                }
            </div>
            <ProductCard lista = {produtosexibidos} onAddToCart={onAddToCart}/>
        </div>
    )
}